######################################################################
# Automatically generated by qmake (3.0) Wed Aug 3 11:24:18 2016
######################################################################

TEMPLATE = app
TARGET = Pipe
INCLUDEPATH += .
QMAKE_CXXFLAGS += -std=c++11
QT += core gui widgets
win32:RC_ICONS += resources/versalogo.ico

# Input
HEADERS += mainwindow.h infowindow.h
SOURCES += main.cpp
RESOURCES += resource.qrc

